# Generated by Django 5.2.8 on 2026-09-12 22:15

import EVA.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVA', '0002_justificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencia',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterModelOptions(
            name='justificacion',
            options={'ordering': ['-fecha_envio']},
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente'), ('Justificado', 'Justificado')], default='Presente', max_length=20),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='justificacion',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='justificaciones/', validators=[EVA.validators.validar_documento]),
        ),
        migrations.AlterField(
            model_name='justificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='asistencia',
            constraint=models.UniqueConstraint(fields=('usuario', 'fecha'), name='unique_asistencia_usuario_fecha'),
        ),
    ]
